// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPSc-oh8TtKAH5_aZgMIJcRABM6yfD8pA',
    appId: '1:273110823684:web:6e81f448c237ec9ccb1651',
    messagingSenderId: '273110823684',
    projectId: 'student-directry-app',
    authDomain: 'student-directry-app.firebaseapp.com',
    storageBucket: 'student-directry-app.firebasestorage.app',
    measurementId: 'G-9BHD3PF1TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsRhGfclgZdlUVVwZ4UX9YoW1UK8VrNaw',
    appId: '1:273110823684:android:6e43a602e2cccca3cb1651',
    messagingSenderId: '273110823684',
    projectId: 'student-directry-app',
    storageBucket: 'student-directry-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1kfYFNhHQfbJyzQTDiLeSSYCQ1W1Q7s',
    appId: '1:273110823684:ios:50f32ab3c8f74d08cb1651',
    messagingSenderId: '273110823684',
    projectId: 'student-directry-app',
    storageBucket: 'student-directry-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1kfYFNhHQfbJyzQTDiLeSSYCQ1W1Q7s',
    appId: '1:273110823684:ios:50f32ab3c8f74d08cb1651',
    messagingSenderId: '273110823684',
    projectId: 'student-directry-app',
    storageBucket: 'student-directry-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPSc-oh8TtKAH5_aZgMIJcRABM6yfD8pA',
    appId: '1:273110823684:web:b95a8016d4e267e2cb1651',
    messagingSenderId: '273110823684',
    projectId: 'student-directry-app',
    authDomain: 'student-directry-app.firebaseapp.com',
    storageBucket: 'student-directry-app.firebasestorage.app',
    measurementId: 'G-MG8B5SWR2F',
  );
}
